"""create geofence rules table

Revision ID: 1209e6762a31
Revises: aa35239e66f3
Create Date: 2026-09-29 22:04:08.148099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1209e6762a31'
down_revision: Union[str, Sequence[str], None] = 'aa35239e66f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geofence_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geofence_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geofence_rules_geofence_id'), 'geofence_rules', ['geofence_id'], unique=False)
    op.create_index(op.f('ix_geofence_rules_id'), 'geofence_rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_geofence_rules_id'), table_name='geofence_rules')
    op.drop_index(op.f('ix_geofence_rules_geofence_id'), table_name='geofence_rules')
    op.drop_table('geofence_rules')
    # ### end Alembic commands ###
